export const JOIN_ROOM_SAGA_EVENT = 'JOIN_ROOM_SAGA_EVENT';
export const JOIN_ROOM_SAGA_WATCH = 'JOIN_ROOM_SAGA_WATCH';
export const LEAVED_ROOM_SAGA_EVENT = 'LEAVED_ROOM_SAGA_EVENT';
export const LEAVE_ROOM_SAGA_WATCH = 'LEAVE_ROOM_SAGA_WATCH';
export const MESSAGE_SAGA_EVENT = 'MESSAGE_SAGA_EVENT';
export const MESSAGE_SAGA_WATCH = 'MESSAGE_SAGA_WATCH';
export const ROOM_USER_LIST_SAGA_EVENT = 'ROOM_USER_LIST_SAGA_EVENT';
export const SET_NICK_SAGA_EVENT = 'SET_NICK_SAGA_EVENT';
export const SET_NICK_SAGA_WATCH = 'SET_NICK_SAGA_WATCH';
export const PING_SAGA_WATCH = 'PING_SAGA_WATCH';
export const CONNECT_SAGA_PUT = 'CONNECT_SAGA_PUT';
export const RECONNECTING = 'RECONNECTING';
export const RECONNECT = 'RECONNECT';


export const SELECT_ROOM = 'SELECT_ROOM';
